SELECT DISTINCT CART_ID
FROM CART_PRODUCTS C
WHERE (CART_ID, 'Yogurt') IN (SELECT CART_ID, NAME FROM CART_PRODUCTS WHERE C.CART_ID = CART_ID)
AND (CART_ID, 'Milk') IN (SELECT CART_ID, NAME FROM CART_PRODUCTS WHERE C.CART_ID = CART_ID)
ORDER BY 1;
