SELECT ins.ANIMAL_ID, ins.ANIMAL_TYPE, ins.NAME
FROM ANIMAL_INS ins
JOIN ANIMAL_OUTS outs
ON ins.ANIMAL_ID = outs.ANIMAL_ID
    AND ins.SEX_UPON_INTAKE LIKE 'intact%'
    AND outs.SEX_UPON_OUTCOME NOT LIKE 'intact%'
ORDER BY ANIMAL_ID;
