SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I, ANIMAL_OUTS O
WHERE I.ANIMAL_ID = O.ANIMAL_ID 
      AND SUBSTR(I.SEX_UPON_INTAKE, 0, INSTR(I.SEX_UPON_INTAKE, ' ') - 1) = 'Intact'
      AND SUBSTR(O.SEX_UPON_OUTCOME, 0, INSTR(O.SEX_UPON_OUTCOME, ' ') - 1) IN ('Spayed', 'Neutered')
ORDER BY 1;
